id: P8ED67086
initial_creation_type: input
source_metadata:
  title: Drāmiḍāvidyārājā
  language: bo
  volumes:
    e8f9b3b527914f199f3a6c9e151c7cfe:
      title: Colophon
      base_file: Colophon.txt
      work_id: W77B20BA0
    309b2bec9a644e098ab4c983449d9260:
      title: DHARAṆĪPADA OF ŚAKRA DEVĀNĀMINDRA
      base_file: DHARAṆĪPADA OF ŚAKRA DEVĀNĀMINDRA.txt
      work_id: WB559BE24
    e3d56b5c77454ce3aeed38d71f4103fc:
      title: DHĀRAṆĪPADA OF GUHYAPATI VAJRAPĀṆI
      base_file: DHĀRAṆĪPADA OF GUHYAPATI VAJRAPĀṆI.txt
      work_id: W99EA239C
    ab0e8bb73199471aa2000465eef535fd:
      title: Preface
      base_file: Preface.txt
      work_id: W5424D2DF
    96efdc0c1ba6487ca2707ab0046e737b:
      title: THE DHARAṆĪMANTRAPADA OF THE FOUR GREAT KINGS
      base_file: THE DHARAṆĪMANTRAPADA OF THE FOUR GREAT KINGS.txt
      work_id: W992A8DBB
    6aa317e0290941e1b1d727da41222c92:
      title: THE DHĀRAṆĪMANTRAPADA OF BRAHMĀ SAHAMPATI
      base_file: THE DHĀRAṆĪMANTRAPADA OF BRAHMĀ SAHAMPATI.txt
      work_id: WE579C515
    d24fa4de9d5e41e78ceb38084fa48cc9:
      title: THE MANTRA SPOKEN BY ĀRYA AVALOKITEŚVARA
      base_file: THE MANTRA SPOKEN BY ĀRYA AVALOKITEŚVARA.txt
      work_id: W52034600
    5fc1fcb4c620454b9f4a8d34680bc179:
      title: THE NĀGA KINGS
      base_file: THE NĀGA KINGS.txt
      work_id: W4B41880D
    e09a5f1d19a241bcb8d86e507563aa0d:
      title: Title
      base_file: Title.txt
      work_id: W55EE58CC
  chapter_to_tile: {}
created_at: '2022-03-01T21:22:54.092552'
last_modified_at: '2022-03-01T21:22:54.092558'
